- name: install ru locale
  ansible.builtin.dnf:
    name: glibc-langpack-ru
    state: present

- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: Install Vim
  ansible.builtin.dnf:
    name: vim
    state: present